### ISSUE TITLE
Does train encode  not need normalized  ??

### ISSUE THREAD

**Issue by Johnson-yue** [orpatashnik/BalaGAN#2]
https://github.com/orpatashnik/BalaGAN/blob/08552de5078d02d82b7e9f049836dd47d4159295/data.py#L91

**Comment by orpatashnik** [comment]
My implementation is highly based on https://github.com/sthalles/SimCLR which does not use normalization as well.
Actually, I also noticed that the images are not normalized which is a bit strange, but since it works well as it is I didn't try to add normalization.

**Comment by Johnson-yue** [comment]
@orpatashnik  thank you for reply， I will try it
